insert into public.deals (
  id, cruise_line, ship_name, departure_port, destination, nights, starting_price, sail_date, image, image_alt, deal_url, last_checked, category
) values
('pc-wonder-3n-bahamas', 'Royal Caribbean', 'Wonder of the Seas', 'Port Canaveral', 'Nassau & Perfect Day at CocoCay', 3, 279, '2026-05-15', '/images/private-island-cruise.webp', 'Royal Caribbean cruise ship near a bright Bahamas private island', 'https://www.royalcaribbean.com/', '2026-04-27T08:15:00-04:00', 'last-minute'),
('mia-celebration-4n-bahamas', 'Carnival', 'Carnival Celebration', 'Miami', 'Bahamas', 4, 259, '2026-05-22', '/images/miami-cruise-port.webp', 'Carnival cruise ship departing the Miami cruise port', 'https://www.carnival.com/', '2026-04-27T08:05:00-04:00', 'family'),
('fll-sun-princess-7n-caribbean', 'Princess Cruises', 'Sun Princess', 'Fort Lauderdale', 'Eastern Caribbean', 7, 549, '2026-06-07', '/images/fort-lauderdale-cruise-port.webp', 'Princess cruise ship departing Fort Lauderdale at golden hour', 'https://www.princess.com/', '2026-04-27T07:55:00-04:00', 'standard'),
('tpa-paradise-5n-western', 'Carnival', 'Carnival Paradise', 'Tampa', 'Cozumel & Grand Cayman', 5, 329, '2026-05-30', '/images/cruise-sunset-sea.webp', 'Cruise ship sailing at sunset on a Western Caribbean route', 'https://www.carnival.com/', '2026-04-27T08:20:00-04:00', 'standard'),
('jax-elation-4n-bahamas', 'Carnival', 'Carnival Elation', 'Jacksonville', 'Freeport & Nassau', 4, 239, '2026-05-18', '/images/cruise-bow-horizon.webp', 'Cruise ship bow facing a clear ocean horizon from Jacksonville', 'https://www.carnival.com/', '2026-04-27T08:02:00-04:00', 'last-minute'),
('mia-msc-seashore-3n-ocean-cay', 'MSC Cruises', 'MSC Seashore', 'Miami', 'Ocean Cay MSC Marine Reserve', 3, 199, '2026-05-08', '/images/bahamas-cruise-beach.webp', 'Bahamas cruise beach destination with turquoise water', 'https://www.msccruisesusa.com/', '2026-04-27T08:30:00-04:00', 'last-minute'),
('pc-disney-treasure-4n-bahamas', 'Disney Cruise Line', 'Disney Treasure', 'Port Canaveral', 'Castaway Cay & Nassau', 4, 749, '2026-06-12', '/images/family-cruise-pool-deck.webp', 'Family cruise pool deck on a sunny Port Canaveral sailing', 'https://disneycruise.disney.go.com/', '2026-04-27T07:45:00-04:00', 'family'),
('fll-holland-eurodam-10n-southern', 'Holland America', 'Eurodam', 'Fort Lauderdale', 'Southern Caribbean', 10, 699, '2026-07-04', '/images/luxury-cruise-terrace.webp', 'Luxury cruise terrace overlooking the Southern Caribbean', 'https://www.hollandamerica.com/', '2026-04-27T07:38:00-04:00', 'standard'),
('mia-ncl-encore-7n-western', 'Norwegian Cruise Line', 'Norwegian Encore', 'Miami', 'Western Caribbean', 7, 499, '2026-06-21', '/images/caribbean-island-beach.webp', 'Western Caribbean island beach with a cruise ship offshore', 'https://www.ncl.com/', '2026-04-27T08:10:00-04:00', 'family'),
('tpa-rhapsody-6n-belize', 'Royal Caribbean', 'Rhapsody of the Seas', 'Tampa', 'Belize & Cozumel', 6, 389, '2026-06-02', '/images/cruise-sunset-sea.webp', 'Royal Caribbean ship sailing toward Belize and Cozumel at sunset', 'https://www.royalcaribbean.com/', '2026-04-27T08:18:00-04:00', 'standard'),
('pc-msc-grandiosa-7n-caribbean', 'MSC Cruises', 'MSC Grandiosa', 'Port Canaveral', 'Caribbean & Ocean Cay', 7, 449, '2026-06-28', '/images/cruise-port-departure.webp', 'MSC cruise ship leaving Port Canaveral for the Caribbean', 'https://www.msccruisesusa.com/', '2026-04-27T08:12:00-04:00', 'family'),
('fll-celebrity-beyond-6n-eastern', 'Celebrity Cruises', 'Celebrity Beyond', 'Fort Lauderdale', 'Grand Cayman & Bahamas', 6, 579, '2026-06-14', '/images/luxury-cruise-deck.webp', 'Celebrity cruise deck lounge on an Eastern Caribbean sailing', 'https://www.celebritycruises.com/', '2026-04-27T07:50:00-04:00', 'standard'),
('mia-virgin-scarlet-4n-key-west', 'Virgin Voyages', 'Scarlet Lady', 'Miami', 'Key West & Bimini', 4, 298, '2026-05-10', '/images/miami-cruise-port.webp', 'Virgin Voyages cruise ship leaving Miami for a weekend getaway', 'https://www.virginvoyages.com/', '2026-04-27T08:26:00-04:00', 'last-minute'),
('jax-elation-5n-princess-cays', 'Carnival', 'Carnival Elation', 'Jacksonville', 'Princess Cays & Nassau', 5, 319, '2026-06-08', '/images/bahamas-cruise-beach.webp', 'Princess Cays Bahamas beach destination for a Jacksonville cruise', 'https://www.carnival.com/', '2026-04-27T07:58:00-04:00', 'family'),
('pc-independence-4n-cococay', 'Royal Caribbean', 'Independence of the Seas', 'Port Canaveral', 'CocoCay & Nassau', 4, 289, '2026-05-25', '/images/private-island-cruise.webp', 'Royal Caribbean ship near CocoCay during a Bahamas sailing', 'https://www.royalcaribbean.com/', '2026-04-27T08:21:00-04:00', 'family'),
('tpa-celebrity-constellation-5n-mexico', 'Celebrity Cruises', 'Celebrity Constellation', 'Tampa', 'Costa Maya & Cozumel', 5, 429, '2026-06-19', '/images/luxury-cruise-terrace.webp', 'Premium cruise balcony terrace on a Mexico sailing from Tampa', 'https://www.celebritycruises.com/', '2026-04-27T07:42:00-04:00', 'standard'),
('mia-ncl-sky-3n-bahamas', 'Norwegian Cruise Line', 'Norwegian Sky', 'Miami', 'Great Stirrup Cay & Nassau', 3, 219, '2026-05-16', '/images/cruise-bow-horizon.webp', 'Norwegian cruise ship view over the ocean toward the Bahamas', 'https://www.ncl.com/', '2026-04-27T08:33:00-04:00', 'last-minute'),
('fll-emerald-princess-8n-aruba', 'Princess Cruises', 'Emerald Princess', 'Fort Lauderdale', 'Aruba, Curacao & Bonaire', 8, 639, '2026-07-12', '/images/caribbean-island-beach.webp', 'Southern Caribbean beach with clear water near Aruba and Bonaire', 'https://www.princess.com/', '2026-04-27T07:36:00-04:00', 'standard')
on conflict (id) do update set
  cruise_line = excluded.cruise_line,
  ship_name = excluded.ship_name,
  departure_port = excluded.departure_port,
  destination = excluded.destination,
  nights = excluded.nights,
  starting_price = excluded.starting_price,
  sail_date = excluded.sail_date,
  image = excluded.image,
  image_alt = excluded.image_alt,
  deal_url = excluded.deal_url,
  last_checked = excluded.last_checked,
  category = excluded.category,
  updated_at = now();
